### PR TITLE
Feechanges

### PR DESCRIPTION
**Pull request by tomt1664**
Fixed fee rate (basis points) instead of absolute amount

No fee output on deposit if the fee is set to zero.

Withdrawal fees included in backup transactions (+ server verification of this). 

SC expiry locktime included in client balance list. 

Get-backup tx wallet function. 

Mainstay attestation failure exception handling - doesn't stop deposit or transfer, writes error to log.

### CODE REVIEW

**Comment by lawlawlaw** [comment]
error[E0308]: mismatched types
   --> integration-tests/src/lib.rs:416:13
    |
416 |         let (_, wallet_sc_ids, bals) = wallets[swap_map[i].1].get_state_chains_info().unwrap();
    |             ^^^^^^^^^^^^^^^^^^^^^^^^   ------------------------------------------------------- this expression has type `(Vec<Uuid>, Vec<Uuid>, Vec<electrumx_client::response::GetBalanceResponse>, Vec<u32>)`
    |             |
    |             expected a tuple with 4 elements, found one with 3 elements
    |
    = note: expected tuple `(Vec<Uuid>, Vec<Uuid>, Vec<electrumx_client::response::GetBalanceResponse>, Vec<u32>)`
               found tuple `(_, _, _)`

**Comment by tomt1664** [comment]
Fixes https://github.com/commerceblock/mercury/issues/94

**Comment by lawlawlaw** [comment]
Integration tests are failing:

---- batch_transfer_test::tests::test_batch_sigs stdout ----
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: StateEntityError("Error: database error: ERROR: column \"locktime\" of relation \"backuptxs\" does not exist")', integration-tests/src/lib.rs:202:63
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by tomossomot** [comment]
> Integration tests are failing:
> 
> ---- batch_transfer_test::tests::test_batch_sigs stdout ----
> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: StateEntityError("Error: database error: ERROR: column "pdldecommit" of relation "ecdsa" does not exist")', client/src/ecdsa/keygen.rs:59:87
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

@lawlawlaw Reset dbs.

**Review by tomossomot — APPROVED** [review]

**Pull request merged**
